package hibernate;
// Generated 24/09/2011 16:54:31 by Hibernate Tools 3.2.1.GA

import com.mysql.jdbc.TimeUtil;
import com.sun.mail.handlers.text_html;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.GregorianCalendar;

/**
 * Logs generated by hbm2java
 */
public class Logs {

    private Integer id;
    private String data;
    private String info;

    public Logs(String data, String info) {
        this.data = data;
        this.info = info;
    }

    public Logs() {
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getData() {
        return this.data;
    }

    public void setData(String data) {
        this.data = data;
    }

    public String getInfo() {
        return this.info;
    }

    public void setInfo(String info) {
        this.info = info;
    }

    public void setDataNow() {
        Date date = new GregorianCalendar().getTime();
        data = new SimpleDateFormat ("yyyy-MM-dd HH:mm:ss").format(date);
        System.out.println(data);
    }
}
