package hibernatemarcel;
// Generated 24/09/2011 16:54:31 by Hibernate Tools 3.2.1.GA



/**
 * Usuarios generated by hbm2java
 */
public class Usuarios{


     private Integer id;
     private String login;
     private String email;
     private String nome;
     private String senha;
     private int flAdmin;

    public Usuarios() {
    }

    public Usuarios(String login, String email, String nome, String senha, int flAdmin) {
       this.login = login;
       this.email = email;
       this.nome = nome;
       this.senha = senha;
       this.flAdmin = flAdmin;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getLogin() {
        return this.login;
    }
    
    public void setLogin(String login) {
        this.login = login;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getFlAdmin() {
        return this.flAdmin;
    }
    
    public void setFlAdmin(int flAdmin) {
        this.flAdmin = flAdmin;
    }




}


